#include "TargetRegistry.h"

#include "BrowserProfiles.h"

#include <KApplicationTrader>
#include <KService>
#include <KServiceAction>
#include <KShell>

#include <QFileInfo>
#include <QSet>
#include <QStandardPaths>

#include <algorithm>

namespace Lob
{

namespace
{

// Desktop ids that are never real routing destinations: PWA/web-app stubs
// generated by browsers, and rival link routers (including any older build of
// ourselves) which would bounce the URL straight back.
const QStringList kSkipIdPrefixes = {
    QStringLiteral("ffpwa-"),
    QStringLiteral("userapp-"),
    QStringLiteral("firefoxpwa"),
    QStringLiteral("browser_integration"),
    QStringLiteral("browsertamer"),
    QStringLiteral("junction"),
    QStringLiteral("app.lane.Lane"),
};

QString firstExecToken(const KService::Ptr &service)
{
    KShell::Errors error = KShell::NoError;
    const QStringList args = KShell::splitArgs(service->exec(), KShell::NoOptions, &error);
    if (error != KShell::NoError || args.isEmpty()) {
        return {};
    }
    return args.constFirst();
}

QString resolveExecPath(const QString &token)
{
    if (token.isEmpty()) {
        return {};
    }
    const QString found = token.contains(QLatin1Char('/')) ? token : QStandardPaths::findExecutable(token);
    if (found.isEmpty()) {
        return {};
    }
    return QFileInfo(found).absoluteFilePath();
}

/// Lowercased blob of every identifying field. StartupWMClass is often the most
/// stable of them, so it is worth folding in alongside the exec name.
QString fingerprint(const KService::Ptr &service, const QString &execBasename)
{
    const QString wmClass = service->property<QString>(QStringLiteral("StartupWMClass"));
    return (execBasename + QLatin1Char(' ') + service->name() + QLatin1Char(' ') + service->desktopEntryName()
            + QLatin1Char(' ') + wmClass)
        .toLower();
}

EngineFamily guessFamily(const QString &print)
{
    static const QStringList gecko = {
        QStringLiteral("firefox"),
        QStringLiteral("librewolf"),
        QStringLiteral("waterfox"),
        QStringLiteral("floorp"),
        QStringLiteral("zen"),
        QStringLiteral("mullvad-browser"),
        QStringLiteral("icecat"),
    };
    static const QStringList chromium = {
        QStringLiteral("chrome"),
        QStringLiteral("chromium"),
        QStringLiteral("edge"),
        QStringLiteral("brave"),
        QStringLiteral("vivaldi"),
        QStringLiteral("opera"),
        QStringLiteral("thorium"),
    };

    for (const QString &needle : gecko) {
        if (print.contains(needle)) {
            return EngineFamily::Gecko;
        }
    }
    for (const QString &needle : chromium) {
        if (print.contains(needle)) {
            return EngineFamily::Chromium;
        }
    }
    return EngineFamily::Unknown;
}

/// Reads the private-window flag out of the entry's own desktop action. Matched
/// on the action id, never the display text -- Edge's reads "New InPrivate
/// Window" and Chrome's "New Incognito Window", and both are translated.
QString privateFlagFor(const KService::Ptr &service, EngineFamily family)
{
    const auto actions = service->actions();
    for (const KServiceAction &action : actions) {
        if (action.name() != QLatin1String("new-private-window")) {
            continue;
        }
        KShell::Errors error = KShell::NoError;
        const QStringList args = KShell::splitArgs(action.exec(), KShell::NoOptions, &error);
        if (error != KShell::NoError) {
            continue;
        }
        for (const QString &arg : args) {
            if (arg.startsWith(QLatin1Char('-'))) {
                return arg;
            }
        }
    }

    switch (family) {
    case EngineFamily::Gecko:
        return QStringLiteral("--private-window");
    case EngineFamily::Chromium:
        return QStringLiteral("--incognito");
    case EngineFamily::Unknown:
        return {};
    }
    return {};
}

QString findDataDir(const QString &execBasename, const QString &storageId, EngineFamily family)
{
    if (family == EngineFamily::Gecko) {
        const auto candidates = geckoDataDirCandidates(execBasename, storageId);
        for (const QString &dir : candidates) {
            if (isGeckoDataDir(dir)) {
                return dir;
            }
        }
    } else if (family == EngineFamily::Chromium) {
        const auto candidates = chromiumDataDirCandidates(execBasename, storageId);
        for (const QString &dir : candidates) {
            if (isChromiumDataDir(dir)) {
                return dir;
            }
        }
    }
    return {};
}

/// A known engine is proof enough. Failing that, we trust the entry's own
/// declaration: Categories=WebBrowser is how a browser announces itself, and it
/// is what separates a real browser from an app like chatgpt.desktop that
/// registers for https only to catch OAuth callbacks.
bool isBrowser(const KService::Ptr &service, EngineFamily family)
{
    if (family != EngineFamily::Unknown) {
        return true;
    }
    return service->categories().contains(QLatin1String("WebBrowser"), Qt::CaseInsensitive);
}

bool shouldSkip(const KService::Ptr &service, const QString &ownStorageId)
{
    if (service->storageId() == ownStorageId) {
        return true;
    }
    const QString entryName = service->desktopEntryName();
    for (const QString &prefix : kSkipIdPrefixes) {
        if (entryName.startsWith(prefix, Qt::CaseInsensitive)) {
            return true;
        }
    }
    return false;
}

} // namespace

QList<Target> TargetRegistry::discover(const QString &ownStorageId)
{
    const KService::List services = KApplicationTrader::queryByMimeType(
        QStringLiteral("x-scheme-handler/https"),
        [&ownStorageId](const KService::Ptr &service) {
            // queryByMimeType applies no filtering of its own beyond this
            // lambda -- NoDisplay in particular is ours to handle, and on Arch
            // it is exactly what distinguishes microsoft-edge.desktop from its
            // com.microsoft.Edge.desktop twin.
            if (service->noDisplay()) {
                return false;
            }
            if (service->exec().isEmpty()) {
                return false;
            }
            return !shouldSkip(service, ownStorageId);
        });

    QList<Target> targets;
    QSet<QString> seen; // execPath + '\0' + dataDir

    for (const KService::Ptr &service : services) {
        const QString execToken = firstExecToken(service);
        const QString execPath = resolveExecPath(execToken);
        if (execPath.isEmpty()) {
            continue;
        }

        const QString execBasename = QFileInfo(execPath).fileName();
        const QString storageId = service->storageId();

        // Fingerprint decides the engine, which decides the launch flags. The
        // profile store is a separate question: finding it unlocks per-profile
        // targets, but not finding it must not demote a real browser. Firefox
        // that has never been launched has no ~/.mozilla yet and is still a
        // browser -- on this machine it is the current default one.
        const EngineFamily family = guessFamily(fingerprint(service, execBasename));
        const QString dataDir = findDataDir(execBasename, storageId, family);

        const QString dedupKey = execPath + QLatin1Char('\0') + dataDir;
        if (seen.contains(dedupKey)) {
            continue;
        }
        seen.insert(dedupKey);

        Target base;
        base.storageId = storageId;
        base.execPath = execPath;
        base.iconName = service->icon();
        base.label = service->name();
        base.family = family;
        base.dataDir = dataDir;
        base.kind = isBrowser(service, family) ? TargetKind::Browser : TargetKind::OtherHandler;
        base.privateFlag = privateFlagFor(service, family);
        base.id = storageId;

        QList<ProfileInfo> profiles;
        if (family == EngineFamily::Gecko) {
            profiles = scanGeckoProfiles(dataDir);
        } else if (family == EngineFamily::Chromium) {
            profiles = scanChromiumProfiles(dataDir);
        }

        // A browser with one profile is just the browser -- splitting it into a
        // parent plus a single child would only add noise to the picker. We
        // still record which profile that is, so "found exactly one" stays
        // distinguishable from "the scanner failed", and so the launcher can be
        // explicit rather than relying on the browser's own default.
        if (profiles.size() < 2) {
            if (profiles.size() == 1) {
                base.profileKey = profiles.constFirst().key;
                base.profileName = profiles.constFirst().name;
                base.isDefaultProfile = profiles.constFirst().isDefault;
            }
            targets.append(base);
            continue;
        }

        for (const ProfileInfo &profile : std::as_const(profiles)) {
            Target target = base;
            target.profileKey = profile.key;
            target.profileName = profile.name;
            target.isDefaultProfile = profile.isDefault;
            target.id = storageId + QLatin1Char('#') + profile.key;
            target.label = base.label + QStringLiteral(" — ") + profile.name;
            targets.append(target);
        }
    }

    // Browsers first; other handlers are opt-in and sort below them.
    //
    // Within each group the order is alphabetical rather than whatever
    // KApplicationTrader returned: that is sorted by mimeapps preference and
    // shifts as associations change, which would silently reassign the picker's
    // digit shortcuts between one link and the next. A shortcut you cannot
    // trust is worse than no shortcut.
    std::sort(targets.begin(), targets.end(), [](const Target &a, const Target &b) {
        const bool aBrowser = a.kind == TargetKind::Browser;
        const bool bBrowser = b.kind == TargetKind::Browser;
        if (aBrowser != bBrowser) {
            return aBrowser;
        }
        const int byLabel = a.label.localeAwareCompare(b.label);
        return byLabel != 0 ? byLabel < 0 : a.id < b.id;
    });

    return targets;
}

} // namespace Lob
