#include "TargetRegistry.h"

#include "BrowserProfiles.h"
#include "Launcher.h"

#include <KApplicationTrader>
#include <KService>
#include <KServiceAction>
#include <KShell>

#include <QFileInfo>
#include <QHash>
#include <QStandardPaths>
#include <QDir>

#include <algorithm>

namespace Lob
{

namespace
{

constexpr auto kCommandOption = QLatin1String("--command=");
constexpr auto kUserDataDirOption = QLatin1String("--user-data-dir=");
constexpr auto kConfigHomeAssignment = QLatin1String("XDG_CONFIG_HOME=");

// Desktop ids that are never real routing destinations: PWA/web-app stubs
// generated by browsers, and rival link routers (including any older build of
// ourselves) which would bounce the URL straight back.
const QStringList kSkipIdPrefixes = {
    QStringLiteral("ffpwa-"),
    QStringLiteral("userapp-"),
    QStringLiteral("firefoxpwa"),
    QStringLiteral("browser_integration"),
    QStringLiteral("browsertamer"),
    QStringLiteral("junction"),
    QStringLiteral("app.lane.Lane"),
};

QStringList execTokens(const QString &exec)
{
    KShell::Errors error = KShell::NoError;
    const QStringList args = KShell::splitArgs(exec, KShell::AbortOnMeta, &error);
    if (error != KShell::NoError || args.isEmpty()) {
        return {};
    }
    return args;
}

QString resolveExecPath(const QString &token)
{
    if (token.isEmpty()) {
        return {};
    }
    const QString found = token.contains(QLatin1Char('/')) ? token : QStandardPaths::findExecutable(token);
    if (found.isEmpty()) {
        return {};
    }
    return QFileInfo(found).absoluteFilePath();
}

/// Lowercased blob of every identifying field. StartupWMClass is often the most
/// stable of them, so it is worth folding in alongside the exec name.
QString fingerprint(const KService::Ptr &service, const QString &execBasename)
{
    const QString wmClass = service->property<QString>(QStringLiteral("StartupWMClass"));
    return (execBasename + QLatin1Char(' ') + service->name() + QLatin1Char(' ') + service->desktopEntryName()
            + QLatin1Char(' ') + wmClass)
        .toLower();
}

EngineFamily guessFamily(const QString &print)
{
    static const QStringList gecko = {
        QStringLiteral("firefox"),
        QStringLiteral("librewolf"),
        QStringLiteral("waterfox"),
        QStringLiteral("floorp"),
        QStringLiteral("zen"),
        QStringLiteral("mullvad-browser"),
        QStringLiteral("icecat"),
    };
    static const QStringList chromium = {
        QStringLiteral("chrome"),
        QStringLiteral("chromium"),
        QStringLiteral("edge"),
        QStringLiteral("brave"),
        QStringLiteral("vivaldi"),
        QStringLiteral("opera"),
        QStringLiteral("thorium"),
    };

    for (const QString &needle : gecko) {
        if (print.contains(needle)) {
            return EngineFamily::Gecko;
        }
    }
    for (const QString &needle : chromium) {
        if (print.contains(needle)) {
            return EngineFamily::Chromium;
        }
    }
    return EngineFamily::Unknown;
}

/// Flags that mean "private window" in some browser. Not exhaustive by
/// construction -- it is a hint for reading an action, not the only way in.
const QStringList kKnownPrivateFlags = {
    QStringLiteral("--private-window"),   QStringLiteral("-private-window"),
    QStringLiteral("--private"),          QStringLiteral("-private"),
    QStringLiteral("--private-browsing"), QStringLiteral("--incognito"),
    QStringLiteral("--inprivate"),
};

/// Arguments a private-window action may carry that say nothing about privacy.
const QStringList kNotPrivateFlags = {
    QStringLiteral("--new-window"), QStringLiteral("--new-tab"),
    QStringLiteral("--"),           QStringLiteral("--file-forwarding"),
};

/// The flag in a command line that turns it into a private window, if any.
/// Known spellings win; otherwise the first option the entry passes to the
/// application itself is it, which is how forks nobody has heard of still work.
QString privateFlagIn(const QStringList &command)
{
    const int application = Launcher::programIndex(command);
    if (application < 0) {
        return {};
    }
    for (const QString &arg : command) {
        if (kKnownPrivateFlags.contains(arg)) {
            return arg;
        }
    }
    for (int n = application + 1; n < command.size(); ++n) {
        const QString arg = command.at(n);
        if (arg.startsWith(QLatin1Char('-')) && !arg.contains(QLatin1Char('='))
            && !kNotPrivateFlags.contains(arg)) {
            return arg;
        }
    }
    return {};
}

/// Reads the private-window flag out of the entry's own desktop action. Matched
/// on the action id, never the display text -- Edge's reads "New InPrivate
/// Window" and Chrome's "New Incognito Window", and both are translated. Entries
/// that spell the id differently are still caught by the second pass, which
/// accepts only a flag we recognise.
QString privateFlagFor(const KService::Ptr &service, EngineFamily family, const QString &print, QStringList *privateCommand)
{
    const auto actions = service->actions();
    for (bool byName : {true, false}) {
        for (const KServiceAction &action : actions) {
            if (byName != (action.name() == QLatin1String("new-private-window"))) {
                continue;
            }
            const auto args = execTokens(action.exec());
            if (!Launcher::commandIsSafe(args)) {
                continue;
            }
            const QString flag = privateFlagIn(args);
            if (flag.isEmpty() || (!byName && !kKnownPrivateFlags.contains(flag))) {
                continue;
            }
            *privateCommand = args;
            return flag;
        }
    }

    switch (family) {
    case EngineFamily::Gecko:
        return QStringLiteral("--private-window");
    case EngineFamily::Chromium:
        return print.contains(QLatin1String("edge")) ? QStringLiteral("--inprivate") : QStringLiteral("--incognito");
    case EngineFamily::Unknown:
        return {};
    }
    return {};
}

QString findDataDir(const QString &execBasename, const QString &storageId, EngineFamily family, const QString &flatpakId,
                    const QString &configHome, const QString &explicitDataDir)
{
    if (!explicitDataDir.isEmpty()) { return explicitDataDir; }
    const QString sandbox = QDir::homePath() + QStringLiteral("/.var/app/") + flatpakId + QLatin1Char('/');
    const auto scoped = [&](QStringList candidates) {
        if (!flatpakId.isEmpty()) {
            candidates.removeIf([&](const QString &path) { return !path.startsWith(sandbox); });
        } else {
            candidates.removeIf([](const QString &path) { return path.contains(QLatin1String("/.var/app/")); });
            if (!configHome.isEmpty()) {
                const QString normal = QStandardPaths::writableLocation(QStandardPaths::GenericConfigLocation);
                for (auto &path : candidates) {
                    if (path.startsWith(normal + QLatin1Char('/'))) { path.replace(0, normal.size(), configHome); }
                }
            }
        }
        return candidates;
    };
    if (family == EngineFamily::Gecko) {
        const auto candidates = scoped(geckoDataDirCandidates(execBasename, storageId));
        for (const QString &dir : candidates) {
            if (isGeckoDataDir(dir)) {
                return dir;
            }
        }
    } else if (family == EngineFamily::Chromium) {
        const auto candidates = scoped(chromiumDataDirCandidates(execBasename, storageId));
        for (const QString &dir : candidates) {
            if (isChromiumDataDir(dir)) {
                return dir;
            }
        }
    }
    return {};
}

/// A known engine is proof enough. Failing that, we trust the entry's own
/// declaration: Categories=WebBrowser is how a browser announces itself, and it
/// is what separates a real browser from an app like chatgpt.desktop that
/// registers for https only to catch OAuth callbacks.
bool isBrowser(const KService::Ptr &service, EngineFamily family)
{
    if (family != EngineFamily::Unknown) {
        return true;
    }
    return service->categories().contains(QLatin1String("WebBrowser"), Qt::CaseInsensitive);
}

bool shouldSkip(const KService::Ptr &service, const QString &ownStorageId)
{
    if (service->storageId() == ownStorageId) {
        return true;
    }
    const QString entryName = service->desktopEntryName();
    for (const QString &prefix : kSkipIdPrefixes) {
        if (entryName.startsWith(prefix, Qt::CaseInsensitive)) {
            return true;
        }
    }
    return false;
}

} // namespace

Target TargetRegistry::resolve(const QList<Target> &targets, const QString &id, bool remembered)
{
    if (remembered && !id.contains(QLatin1Char('#'))) {
        QList<Target> profiles;
        for (const auto &target : targets) {
            if (target.storageId == id && !target.profileKey.isEmpty()) { profiles.append(target); }
        }
        if (profiles.size() > 1) { return {}; } // a legacy memory cannot identify which profile was intended
        if (profiles.size() == 1) { return profiles.first(); }
    }
    for (const auto &target : targets) {
        if (target.id == id) { return target; }
    }
    return {};
}

QList<Target> TargetRegistry::withoutRedundantProfiles(const QList<Target> &targets)
{
    // The browser's own entry opens whichever profile that browser defaults to,
    // so it and that profile are two names for the same click. Which of the two
    // to leave out depends on which name says more:
    //
    //   - one profile: the browser's name is the better label, so the profile
    //     row goes ("Firefox", not "Firefox — default").
    //   - several: the explicit rows say which profile they open and the bare
    //     row does not, so the bare row goes.
    //   - several, none of them marked default: nothing is dropped, because
    //     which profile the bare row would open is genuinely unknown.
    //
    // Both ids stay resolvable throughout. This decides what is listed, never
    // what a rule or a memory can name.
    struct Browser {
        int profiles = 0;
        bool hasOwnEntry = false;
        bool knowsDefaultProfile = false;
    };

    QHash<QString, Browser> browsers;
    for (const auto &target : targets) {
        Browser &browser = browsers[target.storageId];
        if (target.profileKey.isEmpty()) {
            browser.hasOwnEntry = true;
            continue;
        }
        ++browser.profiles;
        browser.knowsDefaultProfile = browser.knowsDefaultProfile || target.isDefaultProfile;
    }

    QList<Target> listed;
    listed.reserve(targets.size());
    std::copy_if(targets.cbegin(), targets.cend(), std::back_inserter(listed), [&browsers](const Target &target) {
        const Browser browser = browsers.value(target.storageId);
        if (!browser.hasOwnEntry || browser.profiles == 0) {
            return true;
        }
        return target.profileKey.isEmpty() ? browser.profiles == 1 || !browser.knowsDefaultProfile
                                           : browser.profiles > 1;
    });
    return listed;
}

QList<Target> TargetRegistry::discover(const QString &ownStorageId)
{
    const KService::List services = KApplicationTrader::queryByMimeType(
        QStringLiteral("x-scheme-handler/https"),
        [&ownStorageId](const KService::Ptr &service) {
            // queryByMimeType applies no filtering of its own beyond this
            // lambda -- NoDisplay in particular is ours to handle, and on Arch
            // it is exactly what distinguishes microsoft-edge.desktop from its
            // com.microsoft.Edge.desktop twin.
            if (service->noDisplay()) {
                return false;
            }
            if (service->exec().isEmpty()) {
                return false;
            }
            return !shouldSkip(service, ownStorageId);
        });

    return fromServices(services, ownStorageId);
}

QList<Target> TargetRegistry::fromServices(const KService::List &services, const QString &ownStorageId)
{
    QList<Target> targets;

    for (const KService::Ptr &service : services) {
        if (!service || service->noDisplay() || shouldSkip(service, ownStorageId)) { continue; }
        auto command = execTokens(service->exec());
        if (!Launcher::commandIsSafe(command)) { continue; }
        const QString execToken = command.first();
        const QString execPath = resolveExecPath(execToken);
        if (execPath.isEmpty()) {
            continue;
        }

        command[0] = execPath;
        const int program = Launcher::programIndex(command);
        QString configHome;
        for (int n = 1; n < program; ++n) {
            // An entry that relocates the config home relocates the profiles
            // with it, so the scanner has to be told where to look.
            if (command.at(n).startsWith(kConfigHomeAssignment)) {
                configHome = command.at(n).mid(kConfigHomeAssignment.size());
            }
        }
        QString execBasename = QFileInfo(command.value(program)).fileName();
        const QString storageId = service->storageId();
        QString flatpakId;
        int applicationIndex = program;
        if (execBasename == QLatin1String("flatpak")) {
            flatpakId = service->property<QString>(QStringLiteral("X-Flatpak"));
            const QStringList optionsWithValue = {QStringLiteral("--command"), QStringLiteral("--arch"),
                QStringLiteral("--branch"), QStringLiteral("--env"), QStringLiteral("--unset-env"),
                QStringLiteral("--filesystem"), QStringLiteral("--device"), QStringLiteral("--socket"),
                QStringLiteral("--nosocket"), QStringLiteral("--persist"), QStringLiteral("--talk-name"),
                QStringLiteral("--own-name"), QStringLiteral("--system-talk-name"), QStringLiteral("--cwd")};
            for (int n = program + 2; n < command.size(); ++n) {
                if (command.at(n) == QLatin1String("--")) { ++n; applicationIndex = n; break; }
                if (optionsWithValue.contains(command.at(n))) { ++n; continue; }
                if (command.at(n).startsWith(QLatin1Char('-'))) { continue; }
                applicationIndex = n;
                break;
            }
            if (flatpakId.isEmpty()) {
                const auto ref = command.value(applicationIndex);
                flatpakId = ref.startsWith(QLatin1String("app/")) ? ref.section(QLatin1Char('/'), 1, 1)
                                                                               : ref.section(QLatin1Char('/'), 0, 0);
            }
            execBasename.clear();
            for (int n = program + 2; n < applicationIndex; ++n) {
                const auto arg = command.at(n);
                if (arg.startsWith(kCommandOption)) { execBasename = QFileInfo(arg.mid(kCommandOption.size())).fileName(); }
                if (arg == QLatin1String("--command")) { execBasename = QFileInfo(command.value(n + 1)).fileName(); }
            }
            if (execBasename.isEmpty()) {
                static const QMap<QString, QString> flatpakExecutables = {
                    {QStringLiteral("org.mozilla.firefox"), QStringLiteral("firefox")},
                    {QStringLiteral("org.chromium.Chromium"), QStringLiteral("chromium")},
                    {QStringLiteral("com.google.Chrome"), QStringLiteral("google-chrome")},
                    {QStringLiteral("com.microsoft.Edge"), QStringLiteral("microsoft-edge")},
                    {QStringLiteral("com.brave.Browser"), QStringLiteral("brave")},
                    {QStringLiteral("io.gitlab.librewolf-community"), QStringLiteral("librewolf")},
                };
                execBasename = flatpakExecutables.value(flatpakId);
            }
        }
        QString explicitDataDir;
        for (int n = program + 1; n < command.size(); ++n) {
            const auto arg = command.at(n);
            if (arg.startsWith(kUserDataDirOption)) { explicitDataDir = arg.mid(kUserDataDirOption.size()); }
            if (arg == QLatin1String("--user-data-dir")) { explicitDataDir = command.value(n + 1); }
        }

        // Fingerprint decides the engine, which decides the launch flags. The
        // profile store is a separate question: finding it unlocks per-profile
        // targets, but not finding it must not demote a real browser. Firefox
        // that has never been launched has no ~/.mozilla yet and is still a
        // browser -- on this machine it is the current default one.
        const QString print = fingerprint(service, execBasename);
        const EngineFamily family = guessFamily(print);
        const QString dataDir = findDataDir(execBasename, flatpakId.isEmpty() ? storageId : flatpakId + QStringLiteral(".desktop"),
                                            family, flatpakId, configHome, explicitDataDir);

        Target base;
        base.storageId = storageId;
        base.execPath = execPath;
        base.command = command;
        base.applicationName = service->name();
        base.desktopFilePath = service->entryPath();
        base.flatpakId = flatpakId;
        base.browserExecutable = execBasename;
        base.workingDirectory = service->workingDirectory();
        base.terminal = service->terminal();
        base.terminalOptions = service->terminalOptions();
        base.applicationIndex = applicationIndex;
        base.iconName = service->icon();
        base.label = service->name();
        base.family = family;
        base.dataDir = dataDir;
        base.kind = isBrowser(service, family) ? TargetKind::Browser : TargetKind::OtherHandler;
        base.privateFlag = privateFlagFor(service, family, print, &base.privateCommand);
        base.id = storageId;

        QList<ProfileInfo> profiles;
        if (!dataDir.isEmpty() && family == EngineFamily::Gecko) {
            profiles = scanGeckoProfiles(dataDir);
        } else if (!dataDir.isEmpty() && family == EngineFamily::Chromium) {
            profiles = scanChromiumProfiles(dataDir);
        }

        // The bare entry is the browser's own default profile, and stays
        // routable: a rule may deliberately mean "whatever Firefox opens with".
        // Every profile gets its own identity regardless of how many there are
        // today, so an id written down now still means the same thing after a
        // second profile appears. withoutRedundantProfiles() is what keeps the
        // picker from showing one browser twice.
        targets.append(base);

        for (const ProfileInfo &profile : std::as_const(profiles)) {
            Target target = base;
            target.profileKey = profile.key;
            target.profileName = profile.name;
            target.isDefaultProfile = profile.isDefault;
            target.id = storageId + QLatin1Char('#') + profile.key;
            target.label = base.label + QStringLiteral(" — ") + profile.name;
            targets.append(target);
        }
    }

    // Browsers first; other handlers are opt-in and sort below them.
    //
    // Within each group the order is alphabetical rather than whatever
    // KApplicationTrader returned: that is sorted by mimeapps preference and
    // shifts as associations change, which would silently reassign the picker's
    // digit shortcuts between one link and the next. A shortcut you cannot
    // trust is worse than no shortcut.
    std::sort(targets.begin(), targets.end(), [](const Target &a, const Target &b) {
        const bool aBrowser = a.kind == TargetKind::Browser;
        const bool bBrowser = b.kind == TargetKind::Browser;
        if (aBrowser != bBrowser) {
            return aBrowser;
        }
        const int byLabel = a.label.localeAwareCompare(b.label);
        return byLabel != 0 ? byLabel < 0 : a.id < b.id;
    });

    return targets;
}

} // namespace Lob
